service: localstack-demo

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  endpointType: regional
  environment:
    DYNAMODB_ENDPOINT: http://localhost:4566

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - dev
    host: http://localhost
    edgePort: 4566
    autostart: true

functions:
  getUser:
    handler: handler.handler
    timeout: 15
    events:
      - http:
          path: user/{userId}
          method: get
          cors: true
  createUser:
    handler: handler.handler
    events:
      - http:
          path: user
          method: post
          cors: true
